# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - rrrrr_arm_controller
    - rrrrr_finger_controller

  rrrrr_arm_controller:
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_final
    action_ns: follow_joint_trajectory
    default: true
  rrrrr_finger_controller:
    type: GripperCommand
    joints:
      - joint_final
      - finger1_joint
      - finger2_joint
    action_ns: gripper_cmd
    default: true